<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"用户管理",
                       "menuJump":"列表",
                       "tableName":"yonghu"
                   }
               ],
               "menu":"用户管理"
           }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"美食信息管理",
                        "menuJump":"列表",
                        "tableName":"meishi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"美食信息留言管理",
                        "menuJump":"列表",
                        "tableName":"meishiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"美食信息收藏管理",
                        "menuJump":"列表",
                        "tableName":"meishiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"美食订单管理",
                        "menuJump":"列表",
                        "tableName":"meishiOrder"
                    }
                ],
                "menu":"美食信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"博主推荐管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"博主推荐管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"店址管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryDianzhi"
			        }
			    ],
                "menu":"店址管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"口味管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKouwei"
			        }
			
			    ],
			    "menu":"口味管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"美食信息管理",
	                    "menuJump":"列表",
	                    "tableName":"meishi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"美食信息留言管理",
	                    "menuJump":"列表",
	                    "tableName":"meishiLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"美食信息收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"meishiCollection"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"美食订单管理",
	                    "menuJump":"列表",
	                    "tableName":"meishiOrder"
	                }
	            ],
	            "menu":"美食信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"博主推荐管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"博主推荐管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
